sudo: false
language: python

jobs:
  fast_finish: true
  include:
  - python: 2.6
    env: MONGODB=3.4.2
  - python: 2.7
    env: MONGODB=3.2.12
  - python: 3.3
    env: MONGODB=3.0.14
  - python: 3.4
    env: MONGODB=2.6.12
  - python: &latest_py3 3.5
    env: MONGODB=2.4.14
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: HQ6c5wiRDLjfb0XjOuDwfzuagYvQ+QgrFZ2Y6RYbdzJcoWxo6VBfVwq6zgsdldUzl0zHw/1MxWusljUXxneGrn+Ef616tPaRXrIIcYroG479+09woD37u26Xi6M8NBvUxiNRUGvspV5Ja8+88vjisDWwB7sNbEVGhBhoMDqLCew=
      distributions: dists
      skip_cleanup: true

install:
  - pip install -U tox tox-venv
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar zxf mongodb-linux-x86_64-${MONGODB}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/:${PATH}
  - mongod --version

script:
  - tox
